- hosts: togashik
  vars_files:
    - vars/defaults.yml
  sudo: True
  roles:
    - { role: create-deploy-user, tags: ['create-deploy-user'] }


- hosts: togashik
  vars_files:
    - vars/defaults.yml
  remote_user: "{{ deploy }}"
  roles:
    ### Server provisioning roles:
    - { role: linux-prereqs, tags: ['linux-prereqs'] }
    - { role: ufw, tags: ['ufw'] }
    - { role: rbenv, tags: ['rbenv'] }
    - { role: ruby, tags: ['ruby'] }
    - { role: rails, tags: ['rails'] }
